import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  products: [
    {
      id: "1",
      name: "Product 1",
      description: "Description 1111111111111111111111111111111111111",
      rating: "4",
      code: "code1",
      base: "Base 1",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 1",
      surface: "Wood",
      images: [
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      feature: [
        {
          id: "1",
          name: "Feature 1",
          description: "Feature Description 1",
          value: "10%",
        },
        {
          id: "1",
          name: "Feature 2",
          description: "Feature Description 1",
          value: "10%",
        },
      ],
      paint: [
        {
          id: "1",
          price: "100",
          quantity: "10",
          volumn: 18,
          coverage: 3,
          dryingTime: 2,
          layer: 2,
          color: [
            {
              colorID: "1",
              colorName: "Red",
            },
            {
              colorID: "2",
              colorName: "Blue",
            },
            {
              colorID: "3",
              colorName: "Green",
            },
          ],
        },
      ],
    },
    {
      id: "2",
      name: "Product 2",
      description: "Description 2",
      rating: "5",
      code: "code2",
      base: "Base 2",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 2",
      surface: "Metal",
      images: [
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      images: [
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      feature: [
        {
          id: "2",
          name: "Feature 2",
          description: "Feature Description 2",
          value: "20%",
        },
      ],
      paint: [
        {
          id: "2",
          price: "200",
          quantity: "20",
          volumn: 18,
          coverage: 3,
          dryingTime: 2,
          layer: 2,
          color: [
            {
              colorID: "4",
              colorName: "Yellow",
            },
            {
              colorID: "5",
              colorName: "Purple",
            },
            {
              colorID: "6",
              colorName: "Orange",
            },
          ],
        },
      ],
    },
    {
      id: "3",
      name: "Product 3",
      description: "Description 3",
      rating: "3",
      code: "code3",
      base: "Base 3",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 3",
      surface: "Plastic",
      images: [
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      feature: [
        {
          id: "3",
          name: "Feature 3",
          description: "Feature Description 3",
          value: "30%",
        },
      ],
      paint: [
        {
          id: "3",
          price: "300",
          quantity: "30",
          volumn: 18,
          coverage: 3,
          dryingTime: 2,
          layer: 2,
          color: [
            {
              colorID: "7",
              colorName: "Pink",
            },
            {
              colorID: "8",
              colorName: "Brown",
            },
            {
              colorID: "9",
              colorName: "Black",
            },
          ],
        },
      ],
    },
    {
      id: "4",
      name: "Product 4",
      description: "Description 4",
      rating: "2",
      code: "code4",
      base: "Base 4",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 4",
      surface: "Glass",
      images: [
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      feature: [
        {
          id: "4",
          name: "Feature 4",
          description: "Feature Description 4",
          value: "40%",
        },
      ],
      paint: [
        {
          id: "4",
          price: "400",
          quantity: "40",
          volumn: 18,
          coverage: 3,
          dryingTime: 2,
          layer: 2,
          color: [
            {
              colorID: "10",
              colorName: "White",
            },
            {
              colorID: "11",
              colorName: "Gray",
            },
            {
              colorID: "12",
              colorName: "Cyan",
            },
          ],
        },
      ],
    },
    {
      id: "5",
      name: "Product 5",
      description: "Description 5",
      rating: "1",
      code: "code5",
      base: "Base 5",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 5",
      surface: "Concrete",
      images: [
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      feature: [
        {
          id: "5",
          name: "Feature 5",
          description: "Feature Description 5",
          value: "50%",
        },
      ],
      paint: [
        {
          id: "5",
          price: "500",
          quantity: "50",
          volumn: 18,
          coverage: 3,
          dryingTime: 2,
          layer: 2,
          color: [
            {
              colorID: "13",
              colorName: "Magenta",
            },
            {
              colorID: "14",
              colorName: "Lime",
            },
            {
              colorID: "15",
              colorName: "Teal",
            },
          ],
        },
      ],
    },
    {
      id: "6",
      name: "Product 6",
      description: "Description 6",
      rating: "5",
      code: "code6",
      base: "Base 6",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 6",
      surface: "Brick",
      images: [
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      feature: [
        {
          id: "6",
          name: "Feature 6",
          description: "Feature Description 6",
          value: "60%",
        },
      ],
      paint: [
        {
          id: "6",
          price: "600",
          quantity: "60",
          volumn: 18,
          coverage: 3,
          dryingTime: 2,
          layer: 2,
          color: [
            {
              colorID: "16",
              colorName: "Navy",
            },
            {
              colorID: "17",
              colorName: "Olive",
            },
            {
              colorID: "18",
              colorName: "Maroon",
            },
          ],
        },
      ],
    },
    {
      id: "7",
      name: "Product 7",
      description: "Description 7",
      rating: "4",
      code: "code7",
      base: "Base 7",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 7",
      surface: "Stone",
      images: [
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      feature: [
        {
          id: "7",
          name: "Feature 7",
          description: "Feature Description 7",
          value: "70%",
        },
      ],
      paint: [
        {
          id: "7",
          price: "700",
          quantity: "70",
          volumn: 18,
          coverage: 3,
          dryingTime: 2,
          layer: 2,
          color: [
            {
              colorID: "19",
              colorName: "Coral",
            },
            {
              colorID: "20",
              colorName: "Turquoise",
            },
            {
              colorID: "21",
              colorName: "Salmon",
            },
          ],
        },
      ],
    },
    {
      id: "8",
      name: "Product 8",
      description: "Description 8",
      rating: "3",
      code: "code8",
      base: "Base 8",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 8",
      surface: "Tile",
      images: [
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      feature: [
        {
          id: "8",
          name: "Feature 8",
          description: "Feature Description 8",
          value: "80%",
        },
      ],
      paint: [
        {
          id: "8",
          price: "800",
          quantity: "80",
          volumn: 18,
          coverage: 3,
          dryingTime: 2,
          layer: 2,
          color: [
            {
              colorID: "22",
              colorName: "Lavender",
            },
            {
              colorID: "23",
              colorName: "Beige",
            },
            {
              colorID: "24",
              colorName: "Mint",
            },
          ],
        },
      ],
    },
    {
      id: "9",
      name: "Product 9",
      description: "Description 9",
      rating: "2",
      code: "code9",
      base: "Base 9",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 9",
      surface: "Carpet",
      images: [
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      feature: [
        {
          id: "9",
          name: "Feature 9",
          description: "Feature Description 9",
          value: "90%",
        },
      ],
      paint: [
        {
          id: "9",
          price: "900",
          quantity: "90",
          volumn: 18,
          coverage: 3,
          dryingTime: 2,
          layer: 2,
          color: [
            {
              colorID: "25",
              colorName: "Peach",
            },
            {
              colorID: "26",
              colorName: "Ivory",
            },
            {
              colorID: "27",
              colorName: "Gold",
            },
          ],
        },
      ],
    },
    {
      id: "10",
      name: "Product 10",
      description: "Description 10",
      rating: "1",
      code: "code10",
      base: "Base 10",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 10",
      surface: "Marble",
      images: [
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://www.luxcolor.vn/data/product/dc3c2240-2c01-4614-bbd1-cc81f7c36e6b_864102.png",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      feature: [
        {
          id: "10",
          name: "Feature 10",
          description: "Feature Description 10",
          value: "100%",
        },
      ],
      paint: [
        {
          id: "10",
          price: "1000",
          quantity: "100",
          volumn: 18,
          coverage: 3,
          dryingTime: 2,
          layer: 2,
          color: [
            {
              colorID: "28",
              colorName: "Silver",
            },
            {
              colorID: "29",
              colorName: "Bronze",
            },
            {
              colorID: "30",
              colorName: "Copper",
            },
          ],
        },
      ],
    },
    {
      id: "11",
      name: "Product 11",
      description: "Description 11",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 11",
      surface: "Wood",
      feature: [
        {
          id: "11",
          name: "Feature 11",
          description: "Feature Description 11",
          value: "11%",
        },
      ],

      images: [
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      floor: [
        {
          id: "11",
          price: "110",
          quantity: "11",
          size: "3 x 2",
          thickness: "10",
          grain: "Grain 11",
          gloss: "Gloss 11",
          level: "Level 11",
        },
      ],
    },
    {
      id: "12",
      name: "Product 12",
      description: "Description 12",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 12",
      surface: "Wood",
      feature: [
        {
          id: "12",
          name: "Feature 12",
          description: "Feature Description 12",
          value: "12%",
        },
      ],
      images: [
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      floor: [
        {
          id: "12",
          price: "120",
          quantity: "12",
          size: "3 x 2",
          thickness: "10",
          grain: "Grain 12",
          gloss: "Gloss 12",
          level: "Level 12",
        },
      ],
    },
    {
      id: "13",
      name: "Product 13",
      description: "Description 13",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 13",
      surface: "Wood",
      feature: [
        {
          id: "13",
          name: "Feature 13",
          description: "Feature Description 13",
          value: "13%",
        },
      ],
      images: [
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      floor: [
        {
          id: "13",
          price: "130",
          quantity: "13",
          size: "3 x 2",
          thickness: "10",
          grain: "Grain 13",
          gloss: "Gloss 13",
          level: "Level 13",
        },
      ],
    },
    {
      id: "14",
      name: "Product 14",
      description: "Description 14",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 14",
      surface: "Wood",
      feature: [
        {
          id: "14",
          name: "Feature 14",
          description: "Feature Description 14",
          value: "14%",
        },
      ],

      images: [
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      floor: [
        {
          id: "14",
          price: "140",
          quantity: "14",
          size: "3 x 2",
          thickness: "10",
          grain: "Grain 14",
          gloss: "Gloss 14",
          level: "Level 14",
        },
      ],
    },
    {
      id: "15",
      name: "Product 15",
      description: "Description 15",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 15",
      surface: "Wood",
      feature: [
        {
          id: "15",
          name: "Feature 15",
          description: "Feature Description 15",
          value: "15%",
        },
      ],
      images: [
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      floor: [
        {
          id: "15",
          price: "150",
          quantity: "15",
          size: "3 x 2",
          thickness: "10",
          grain: "Grain 15",
          gloss: "Gloss 15",
          level: "Level 15",
        },
      ],
    },
    {
      id: "16",
      name: "Product 16",
      description: "Description 16",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 16",
      surface: "Wood",
      feature: [
        {
          id: "16",
          name: "Feature 16",
          description: "Feature Description 16",
          value: "16%",
        },
      ],
      images: [
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      floor: [
        {
          id: "16",
          price: "160",
          quantity: "16",
          size: "3 x 2",
          thickness: "10",
          grain: "Grain 16",
          gloss: "Gloss 16",
          level: "Level 16",
        },
      ],
    },
    {
      id: "17",
      name: "Product 17",
      description: "Description 17",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 17",
      surface: "Wood",
      feature: [
        {
          id: "17",
          name: "Feature 17",
          description: "Feature Description 17",
          value: "17%",
        },
      ],

      images: [
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      floor: [
        {
          id: "17",
          price: "170",
          quantity: "17",
          size: "3 x 2",
          thickness: "10",
          grain: "Grain 17",
          gloss: "Gloss 17",
          level: "Level 17",
        },
      ],
    },
    {
      id: "18",
      name: "Product 18",
      description: "Description 18",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 18",
      surface: "Wood",
      feature: [
        {
          id: "18",
          name: "Feature 18",
          description: "Feature Description 18",
          value: "18%",
        },
      ],

      images: [
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      floor: [
        {
          id: "18",
          price: "180",
          quantity: "18",
          size: "3 x 2",
          thickness: "10",
          grain: "Grain 18",
          gloss: "Gloss 18",
          level: "Level 18",
        },
      ],
    },
    {
      id: "19",
      name: "Product 19",
      description: "Description 19",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 19",
      surface: "Wood",
      feature: [
        {
          id: "19",
          name: "Feature 19",
          description: "Feature Description 19",
          value: "19%",
        },
      ],

      images: [
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      floor: [
        {
          id: "19",
          price: "190",
          quantity: "19",
          size: "3 x 2",
          thickness: "10",
          grain: "Grain 19",
          gloss: "Gloss 19",
          level: "Level 19",
        },
      ],
    },
    {
      id: "20",
      name: "Product 20",
      description: "Description 20",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 20",
      surface: "Wood",
      feature: [
        {
          id: "20",
          name: "Feature 20",
          description: "Feature Description 20",
          value: "20%",
        },
      ],
      images: [
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://sangobachloc.com.vn/uploads/plugin/product_items/135/san-g-kaindl-k4443-k4443-w.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      floor: [
        {
          id: "20",
          price: "200",
          quantity: "20",
          size: "3 x 2",
          thickness: "10",
          grain: "Grain 20",
          gloss: "Gloss 20",
          level: "Level 20",
        },
      ],
    },
    {
      id: "21",
      name: "Product 21",
      description: "Description 21",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 21",
      surface: "Wood",
      feature: [
        {
          id: "21",
          name: "Feature 21",
          description: "Feature Description 21",
          value: "21%",
        },
      ],
      images: [
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      wallpaper: [
        {
          id: "21",
          price: "210",
          quantity: "21",
          size: "3 x 2",
          material: "Giấy",
        },
      ],
    },
    {
      id: "22",
      name: "Product 22",
      description: "Description 22",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 22",
      surface: "Wood",
      feature: [
        {
          id: "22",
          name: "Feature 22",
          description: "Feature Description 22",
          value: "22%",
        },
      ],
      images: [
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      wallpaper: [
        {
          id: "22",
          price: "220",
          quantity: "22",
          size: "3 x 2",
          material: "Giấy",
        },
      ],
    },
    {
      id: "23",
      name: "Product 23",
      description: "Description 23",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 23",
      surface: "Wood",
      feature: [
        {
          id: "23",
          name: "Feature 23",
          description: "Feature Description 23",
          value: "23%",
        },
      ],
      images: [
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      wallpaper: [
        {
          id: "23",
          price: "230",
          quantity: "23",
          size: "3 x 2",
          material: "Giấy",
        },
      ],
    },
    {
      id: "24",
      name: "Product 24",
      description: "Description 24",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 24",
      surface: "Wood",
      feature: [
        {
          id: "24",
          name: "Feature 24",
          description: "Feature Description 24",
          value: "24%",
        },
      ],
      images: [
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      wallpaper: [
        {
          id: "24",
          price: "240",
          quantity: "24",
          size: "3 x 2",
          material: "Giấy",
        },
      ],
    },
    {
      id: "25",
      name: "Product 25",
      description: "Description 25",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 25",
      surface: "Wood",
      feature: [
        {
          id: "25",
          name: "Feature 25",
          description: "Feature Description 25",
          value: "25%",
        },
      ],
      images: [
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      wallpaper: [
        {
          id: "25",
          price: "250",
          quantity: "25",
          size: "3 x 2",
          material: "Giấy",
        },
      ],
    },
    {
      id: "26",
      name: "Product 26",
      description: "Description 26",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 26",
      surface: "Wood",
      feature: [
        {
          id: "26",
          name: "Feature 26",
          description: "Feature Description 26",
          value: "26%",
        },
      ],
      images: [
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      wallpaper: [
        {
          id: "26",
          price: "260",
          quantity: "26",
          size: "3 x 2",
          material: "Giấy",
        },
      ],
    },
    {
      id: "27",
      name: "Product 27",
      description: "Description 27",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 27",
      surface: "Wood",
      feature: [
        {
          id: "27",
          name: "Feature 27",
          description: "Feature Description 27",
          value: "27%",
        },
      ],
      images: [
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      wallpaper: [
        {
          id: "27",
          price: "270",
          quantity: "27",
          size: "3 x 2",
          material: "Giấy",
        },
      ],
    },
    {
      id: "28",
      name: "Product 28",
      description: "Description 28",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 28",
      surface: "Wood",
      feature: [
        {
          id: "28",
          name: "Feature 28",
          description: "Feature Description 28",
          value: "28%",
        },
      ],
      images: [
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      wallpaper: [
        {
          id: "28",
          price: "280",
          quantity: "28",
          size: "3 x 2",
          material: "Giấy",
        },
      ],
    },
    {
      id: "29",
      name: "Product 29",
      description: "Description 29",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 29",
      surface: "Wood",
      feature: [
        {
          id: "29",
          name: "Feature 29",
          description: "Feature Description 29",
          value: "29%",
        },
      ],
      images: [
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      wallpaper: [
        {
          id: "29",
          price: "290",
          quantity: "29",
          size: "3 x 2",
          material: "Giấy",
        },
      ],
    },
    {
      id: "30",
      name: "Product 30",
      description: "Description 30",
      rating: "3",
      code: "cb23ba",
      base: "Extra White",
      category: {},
      Place_Of_Origin: "VN",
      Warranty: "Warranty 30",
      surface: "Wood",
      feature: [
        {
          id: "30",
          name: "Feature 30",
          description: "Feature Description 30",
          value: "30%",
        },
      ],
      images: [
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
        {
          url: "https://lamquangphat.vn/uploads/aurora/giay-dan-tuong-aurora-4201-1.jpg",
          imageName: "son colux",
          caption: "colux son nha",
          altText: "khi anh kh tim thay",
          type: "THUMBNAIL",
        },
      ],
      wallpaper: [
        {
          id: "30",
          price: "300",
          quantity: "30",
          size: "3 x 2",
          material: "Giấy",
        },
      ],
    },
  ],
};

export const productsSlice = createSlice({
  name: "Products",
  initialState: initialState,
  reducers: {},
});

export default productsSlice.reducer;
