import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  collections: [
    {
      id: 1,
      name: "Designer Color Collection",
      title: "Designer Color Collection",
      content:
        "The Designer Color Collection makes finding the just-right white easier than ever, with our brightest, purest whites and the exquisite colors designers have been asking for. Available in select products.",
      img: "https://s7d2.scene7.com/is/image/sherwinwilliams/dcc-hero-middle?qlt=82&wid=1280&ts=1724081470606&$PNG-Fit$&dpr=off",
      code: "#e9e8e3",
      colors: [
        { id: 1, name: "Crimson", code: "#dc143c" },
        { id: 2, name: "Maroon", code: "#800000" },
        { id: 3, name: "Burgundy", code: "#800020" },
        { id: 4, name: "Dark Scarlet", code: "#560319" },
        { id: 5, name: "Blood Red", code: "#660000" },
        { id: 6, name: "Ruby", code: "#e0115f" },
        { id: 7, name: "Wine", code: "#722f37" },
        { id: 8, name: "Cardinal", code: "#c41e3a" },
        { id: 9, name: "Raspberry", code: "#e30b5d" },
        { id: 10, name: "Dark Cherry", code: "#900020" },
      ],
    },
    {
      id: 2,
      name: "Living Well",
      title: "Living Well",
      content:
        "A collection of colors and paints carefully chosen to invite a sense of comfort, style and well-being into your home.",
      img: "https://s7d2.scene7.com/is/image/sherwinwilliams/CoJo_CollectionPage_LivingWell_Hero1_646x343_hybrid_2x?qlt=82&wid=1280&ts=1705607731118&dpr=off",
      code: "#c8bcab",
      colors: [
        { id: 61, name: "Baby Blue", code: "#89cff0" },
        { id: 62, name: "Powder Blue", code: "#b0e0e6" },
        { id: 63, name: "Sky Blue", code: "#87ceeb" },
        { id: 64, name: "Ice Blue", code: "#afeeee" },
        { id: 65, name: "Periwinkle", code: "#c5d0e6" },
        { id: 66, name: "Cornflower Blue", code: "#6495ed" },
        { id: 67, name: "Robin Egg Blue", code: "#00cccc" },
        { id: 68, name: "Glacier Blue", code: "#71a6d2" },
        { id: 69, name: "Azure Blue", code: "#007fff" },
        { id: 70, name: "Misty Blue", code: "#8cbedd" },
      ],
    },
    {
      id: 3,
      name: "Finest Whites & Neutrals",
      title: "Finest Whites & Neutrals",
      content:
        "Create a space that is quiet and understated or bold and striking. Our most exquisite shades of white and neutral colors come together into a collection versatile enough to do it all, and with stunning coverage you have to see to believe.",
      img: "https://s7d2.scene7.com/is/image/sherwinwilliams/sw-7005-pure-white-living-room-h1?qlt=82&wid=1280&ts=1707336664262&dpr=off",
      code: "#edeae5",
      colors: [
        { id: 121, name: "Forest Green", code: "#228b22" },
        { id: 122, name: "Dark Green", code: "#006400" },
        { id: 123, name: "Hunter Green", code: "#355e3b" },
        { id: 124, name: "Deep Forest Green", code: "#014421" },
        { id: 125, name: "Olive Drab", code: "#6b8e23" },
        { id: 126, name: "Evergreen", code: "#05472a" },
        { id: 127, name: "Teal Green", code: "#006d5b" },
        { id: 128, name: "Emerald Green", code: "#50c878" },
        { id: 129, name: "Pine Green", code: "#01796f" },
        { id: 130, name: "Viridian", code: "#40826d" },
      ],
    },
    {
      id: 4,
      name: "Colormix Forecast",
      title: "Colormix Forecast",
      content:
        "In this ever-evolving world of color, Kolux keeps you in the know and ahead of the trend. Our annual Colormix Forecast explores the rising influences and movements shaping tomorrow's designs through a curated collection of color.",
      img: "https://s7d2.scene7.com/is/image/sherwinwilliams/archive-desktop-hero?qlt=82&wid=1920&ts=1722428648062&dpr=off",
      code: "#71343c",
      colors: [
        { id: 161, name: "Lemon", code: "#fff700" },
        { id: 162, name: "Cornsilk", code: "#fff8dc" },
        { id: 163, name: "Light Gold", code: "#ffec8b" },
        { id: 164, name: "Pale Yellow", code: "#ffff84" },
        { id: 165, name: "Vanilla", code: "#f3e5ab" },
        { id: 166, name: "Cream", code: "#ffffcc" },
        { id: 167, name: "Champagne", code: "#fad6a5" },
        { id: 168, name: "Butter", code: "#fffdd0" },
        { id: 169, name: "Banana", code: "#ffe135" },
        { id: 170, name: "Wheat", code: "#f5deb3" },
      ],
    },
    {
      id: 5,
      name: "Top 50 Colors",
      title: "Top 50 Colors",
      content:
        "Explore our 50 most popular paint colors. Among these loved and trusted hues, you'll find favored grays, whites, neutrals and even some unexpected colors.",
      img: "https://s7d2.scene7.com/is/image/sherwinwilliams/top-50-middle-hero?qlt=82&wid=1280&ts=1716218691266&fmt=png-alpha&bfc=on&fit=constrain&dpr=off",
      code: "#d1cbc1",
      colors: [
        { id: 201, name: "Burnt Orange", code: "#cc5500" },
        { id: 202, name: "Rust", code: "#b7410e" },
        { id: 203, name: "Bronze", code: "#cd7f32" },
        { id: 204, name: "Tangerine", code: "#f28500" },
        { id: 205, name: "Copper", code: "#b87333" },
        { id: 206, name: "Mahogany", code: "#420a1d" },
        { id: 207, name: "Terracotta", code: "#e2725b" },
        { id: 208, name: "Sienna", code: "#a0522d" },
        { id: 209, name: "Clay", code: "#b66a50" },
        { id: 210, name: "Umber", code: "#635147" },
      ],
    },
    {
      id: 6,
      name: "Rejuvenation",
      title: "Rejuvenation",
      content:
        "Rewrite the story of your home with the enduring beauty of Rejuvenation’s color palette. Curated with the brand’s timeless style in mind, this collection of hues pairs seamlessly with Rejuvenation’s customizable lighting and hardware designs.",
      img: "https://s7d2.scene7.com/is/image/sherwinwilliams/rejuvenation-middle-hero?qlt=82&wid=1280&ts=1713799217367&fmt=png-alpha&bfc=on&fit=constrain&dpr=off",
      code: "#666d69",
      colors: [
        { id: 331, name: "Hot Pink", code: "#ff69b4" },
        { id: 332, name: "Rose", code: "#ff007f" },
        { id: 333, name: "Raspberry", code: "#e30b5d" },
        { id: 334, name: "Ruby", code: "#e0115f" },
        { id: 335, name: "Crimson", code: "#dc143c" },
        { id: 336, name: "Cerise", code: "#de3163" },
        { id: 337, name: "Burgundy", code: "#800020" },
        { id: 338, name: "Deep Pink", code: "#ff1493" },
        { id: 339, name: "Fuchsia", code: "#ff00ff" },
        { id: 340, name: "Magenta", code: "#ff00ff" },
      ],
    },
    {
      id: 7,
      name: "West Elm",
      title: "West Elm",
      content:
        "Feel bold with West Elm’s color palette. These carefully curated neutrals and refreshing accent tones will help you design a fresh space that coordinates with their latest collection of modern furnishings.",
      img: "https://s7d2.scene7.com/is/image/sherwinwilliams/Middle-Hero-WE?qlt=82&wid=1280&ts=1714766540304&fmt=png-alpha&bfc=on&fit=constrain&dpr=off",
      code: "#7d9b89",
      colors: [
        { id: 361, name: "Silver", code: "#c0c0c0" },
        { id: 362, name: "Platinum", code: "#e5e4e2" },
        { id: 363, name: "Smoke", code: "#738276" },
        { id: 364, name: "Mist", code: "#c4c4c4" },
        { id: 365, name: "Pearl", code: "#eae0c8" },
        { id: 366, name: "Cloud", code: "#f0f8ff" },
        { id: 367, name: "Dove", code: "#e1e1e1" },
        { id: 368, name: "Fog", code: "#dfe2e5" },
        { id: 369, name: "Lunar Gray", code: "#b2beb5" },
        { id: 370, name: "Gainsboro", code: "#dcdcdc" },
      ],
    },
    {
      id: 8,
      name: "Pottery Barn",
      title: "Pottery Barn",
      content:
        "Make every day beautiful with Pottery Barn brand’s curated color collections. Each palette features hand-selected hues that coordinate with their latest designs, so you can craft a home where color and furniture are paired perfectly.",
      img: "https://s7d2.scene7.com/is/image/sherwinwilliams/pb-mini-palette-middle-hero?qlt=82&wid=1280&ts=1723572963576&dpr=off",
      code: "#cdd2d2",
      colors: [
        { id: 421, name: "Pitch Black", code: "#000000" },
        { id: 422, name: "Jet Black", code: "#080808" },
        { id: 423, name: "Midnight Black", code: "#2b2b2b" },
        { id: 424, name: "Ebony", code: "#555d50" },
        { id: 425, name: "Charcoal", code: "#36454f" },
        { id: 426, name: "Onyx", code: "#353839" },
        { id: 427, name: "Obsidian", code: "#191970" },
        { id: 428, name: "Coal", code: "#080808" },
        { id: 429, name: "Raven", code: "#0e0e10" },
        { id: 430, name: "Soot", code: "#1a1a1a" },
      ],
    },
  ],
};

export const collectionSlice = createSlice({
  name: "Collections",
  initialState: initialState,
  reducers: {},
});

export default collectionSlice.reducer;
