import { createSlice } from "@reduxjs/toolkit";

// const initialState = {
//   colors: [
//     {id: 1, name: "Red", hex: "#ff0000", listhex: ["#b0212a", "#93161f", "#8a181f", "#942425", "#bf4a60"]},
//     {id: 2, name: "Yellow", hex: "#ffff00", listhex: ["#ffb801", "#f8c452", "#ffe298", "#f4d77f", "#efd59c"]},
//     {id: 3, name: "Blue", hex: "#0000ff", listhex: ["#b0212a", "#93161f", "#8a181f", "#942425", "#bf4a60"]},
//     {id: 4, name: "Green", hex: "#008000", listhex: ["#b0212a", "#93161f", "#8a181f", "#942425", "#bf4a60"]},
//     {id: 5, name: "Pink", hex: "#ffc0cb", listhex: ["#b0212a", "#93161f", "#8a181f", "#942425", "#bf4a60"]},
//     {id: 6, name: "Pink", hex: "#ffc0cb", listhex: ["#b0212a", "#93161f", "#8a181f", "#942425", "#bf4a60"]},
//     {id: 7, name: "Pink", hex: "#ffc0cb", listhex: ["#b0212a", "#93161f", "#8a181f", "#942425", "#bf4a60"]},
//     {id: 8, name: "Pink", hex: "#ffc0cb", listhex: ["#b0212a", "#93161f", "#8a181f", "#942425", "#bf4a60"]},
//     {id: 9, name: "Pink", hex: "#ffc0cb", listhex: ["#b0212a", "#93161f", "#8a181f", "#942425", "#bf4a60"]}
//   ],
// };

// content thay bằng description
const initialState = {
  colorFamilies: [
    {
      id: 1,
      name: "Red",
      img: "https://stppgpaints1prd01.blob.core.windows.net/popular-color/popular-color-red-gumball-172-58-62.jpg",
      title: "Red Paint Colors",
      content:
        "Red paint colors can add ruddy farmhouse charm when dark reds are used in dining rooms and living rooms. Brilliant reds can add mid-century feelings to a kitchen, while deep burgundies look incredible in the master bedroom. To find the right red paint colors for your painting project, check out our red color palette below.",
      hex: "#c4736e",
      collections: [
        {
          id: 1,
          name: "Dark Red",
          colors: [
            { id: 1, name: "Crimson", hex: "#dc143c" },
            { id: 2, name: "Maroon", hex: "#800000" },
            { id: 3, name: "Burgundy", hex: "#800020" },
            { id: 4, name: "Dark Scarlet", hex: "#560319" },
            { id: 5, name: "Blood Red", hex: "#660000" },
            { id: 6, name: "Ruby", hex: "#e0115f" },
            { id: 7, name: "Wine", hex: "#722f37" },
            { id: 8, name: "Cardinal", hex: "#c41e3a" },
            { id: 9, name: "Raspberry", hex: "#e30b5d" },
            { id: 10, name: "Dark Cherry", hex: "#900020" },
          ],
        },
        {
          id: 2,
          name: "Light Red",
          colors: [
            { id: 11, name: "Pink", hex: "#ffc0cb" },
            { id: 12, name: "Salmon", hex: "#fa8072" },
            { id: 13, name: "Coral", hex: "#ff7f50" },
            { id: 14, name: "Rose", hex: "#ff007f" },
            { id: 15, name: "Tomato", hex: "#ff6347" },
            { id: 16, name: "Cherry Blossom", hex: "#ffb7c5" },
            { id: 17, name: "Watermelon", hex: "#fc6c85" },
            { id: 18, name: "Strawberry", hex: "#ff5470" },
            { id: 19, name: "Blush", hex: "#de5d83" },
            { id: 20, name: "Carnation", hex: "#ff69b4" },
          ],
        },
        {
          id: 3,
          name: "Deep Red",
          colors: [
            { id: 21, name: "Scarlet", hex: "#ff2400" },
            { id: 22, name: "Fire Brick", hex: "#b22222" },
            { id: 23, name: "Dark Crimson", hex: "#8b0000" },
            { id: 24, name: "Bordeaux", hex: "#800020" },
            { id: 25, name: "Rust", hex: "#b7410e" },
            { id: 26, name: "Mahogany", hex: "#420a1d" },
            { id: 27, name: "Blood Orange", hex: "#d1001c" },
            { id: 28, name: "Vermilion", hex: "#d9381e" },
            { id: 29, name: "Pomegranate", hex: "#c11b17" },
            { id: 30, name: "Ruby Red", hex: "#9b111e" },
          ],
        },
        {
          id: 4,
          name: "Rich Red",
          colors: [
            { id: 31, name: "Ruby", hex: "#e0115f" },
            { id: 32, name: "Garnet", hex: "#733635" },
            { id: 33, name: "Wine Red", hex: "#8b0000" },
            { id: 34, name: "Maroon", hex: "#800000" },
            { id: 35, name: "Brick Red", hex: "#b22222" },
            { id: 36, name: "Fire Engine Red", hex: "#ce2029" },
            { id: 37, name: "Crimson Red", hex: "#990000" },
            { id: 38, name: "Raspberry Red", hex: "#e30b5d" },
            { id: 39, name: "Deep Red", hex: "#8b0000" },
            { id: 40, name: "Burgundy", hex: "#800020" },
          ],
        },
        {
          id: 5,
          name: "Vibrant Red",
          colors: [
            { id: 41, name: "Vermilion", hex: "#d9381e" },
            { id: 42, name: "Coral", hex: "#ff7f50" },
            { id: 43, name: "Tomato Red", hex: "#ff6347" },
            { id: 44, name: "Crimson", hex: "#dc143c" },
            { id: 45, name: "Ruby", hex: "#e0115f" },
            { id: 46, name: "Scarlet", hex: "#ff2400" },
            { id: 47, name: "Fire Engine Red", hex: "#ce2029" },
            { id: 48, name: "Cherry Red", hex: "#ff0800" },
            { id: 49, name: "Pomegranate", hex: "#c11b17" },
            { id: 50, name: "Blood Red", hex: "#660000" },
          ],
        },
      ],
    },
    {
      id: 2,
      name: "Blue",
      img: "https://stppgpaints1prd01.blob.core.windows.net/popular-color/popular-color-keepsakes-192-206-214.jpg",
      title: "Blue Paint Colors",
      content:
        "Blue paint colors add a spritely energy to bedrooms, classic nautical feelings to living spaces, and can really brighten up your bathroom. Check out these gorgeous blue colors for your home below!",
      hex: "#789bc5",
      collections: [
        {
          id: 6,
          name: "Ocean Blue",
          colors: [
            { id: 51, name: "Deep Ocean", hex: "#00008b" },
            { id: 52, name: "Aqua", hex: "#00ffff" },
            { id: 53, name: "Marine Blue", hex: "#000080" },
            { id: 54, name: "Aquamarine", hex: "#7fffd4" },
            { id: 55, name: "Cerulean Blue", hex: "#007ba7" },
            { id: 56, name: "Cyan", hex: "#00ffff" },
            { id: 57, name: "Turquoise", hex: "#40e0d0" },
            { id: 58, name: "Deep Sky Blue", hex: "#00bfff" },
            { id: 59, name: "Pacific Blue", hex: "#1ca9c9" },
            { id: 60, name: "Blueberry", hex: "#1f75fe" },
          ],
        },
        {
          id: 7,
          name: "Pastel Blue",
          colors: [
            { id: 61, name: "Baby Blue", hex: "#89cff0" },
            { id: 62, name: "Powder Blue", hex: "#b0e0e6" },
            { id: 63, name: "Sky Blue", hex: "#87ceeb" },
            { id: 64, name: "Ice Blue", hex: "#afeeee" },
            { id: 65, name: "Periwinkle", hex: "#c5d0e6" },
            { id: 66, name: "Cornflower Blue", hex: "#6495ed" },
            { id: 67, name: "Robin Egg Blue", hex: "#00cccc" },
            { id: 68, name: "Glacier Blue", hex: "#71a6d2" },
            { id: 69, name: "Azure Blue", hex: "#007fff" },
            { id: 70, name: "Misty Blue", hex: "#8cbedd" },
          ],
        },
        {
          id: 8,
          name: "Nautical Blue",
          colors: [
            { id: 71, name: "Navy Blue", hex: "#000080" },
            { id: 72, name: "Slate Blue", hex: "#6a5acd" },
            { id: 73, name: "Steel Blue", hex: "#4682b4" },
            { id: 74, name: "Cadet Blue", hex: "#5f9ea0" },
            { id: 75, name: "Denim Blue", hex: "#1560bd" },
            { id: 76, name: "Cerulean Blue", hex: "#007ba7" },
            { id: 77, name: "Teal Blue", hex: "#367588" },
            { id: 78, name: "Blue Gray", hex: "#6699cc" },
            { id: 79, name: "Powder Blue", hex: "#b0e0e6" },
            { id: 80, name: "Stormy Blue", hex: "#507786" },
          ],
        },
        {
          id: 9,
          name: "Electric Blue",
          colors: [
            { id: 81, name: "Electric Blue", hex: "#7df9ff" },
            { id: 82, name: "Neon Blue", hex: "#00ccff" },
            { id: 83, name: "Light Sky Blue", hex: "#87cefa" },
            { id: 84, name: "Bright Blue", hex: "#0073e6" },
            { id: 85, name: "Vivid Blue", hex: "#005aff" },
            { id: 86, name: "Deep Sky Blue", hex: "#00bfff" },
            { id: 87, name: "Azure Blue", hex: "#007fff" },
            { id: 88, name: "Dodger Blue", hex: "#1e90ff" },
            { id: 89, name: "Cerulean Blue", hex: "#007ba7" },
            { id: 90, name: "Turquoise Blue", hex: "#00ced1" },
          ],
        },
        {
          id: 10,
          name: "Metallic Blue",
          colors: [
            { id: 91, name: "Silver Blue", hex: "#8a8c8e" },
            { id: 92, name: "Steel Blue", hex: "#4682b4" },
            { id: 93, name: "Titanium Blue", hex: "#0f69af" },
            { id: 94, name: "Cobalt Blue", hex: "#0047ab" },
            { id: 95, name: "Cerulean Blue", hex: "#007ba7" },
            { id: 96, name: "Sapphire Blue", hex: "#0f52ba" },
            { id: 97, name: "Royal Blue", hex: "#4169e1" },
            { id: 98, name: "Indigo Blue", hex: "#4b0082" },
            { id: 99, name: "Electric Blue", hex: "#7df9ff" },
            { id: 100, name: "Midnight Blue", hex: "#191970" },
          ],
        },
      ],
    },
    {
      id: 3,
      name: "Green",
      img: "https://stppgpaints1prd01.blob.core.windows.net/popular-color/popular-color-light-sage-178-185-165.jpg",
      title: "Green Paint Colors",
      content:
        "Green paint colors add natural sophistication when used in bedrooms and bathrooms. Deep forest green paint colors and sage green paint colors add earthy peace when used in dining rooms and living rooms.",
      hex: "#b0bf74",
      collections: [
        {
          id: 11,
          name: "Dark Green",
          colors: [
            { id: 101, name: "Forest Green", hex: "#228b22" },
            { id: 102, name: "Hunter Green", hex: "#355e3b" },
            { id: 103, name: "Dark Olive Green", hex: "#556b2f" },
            { id: 104, name: "Army Green", hex: "#4b5320" },
            { id: 105, name: "Deep Green", hex: "#056608" },
            { id: 106, name: "Jungle Green", hex: "#29ab87" },
            { id: 107, name: "Pine Green", hex: "#01796f" },
            { id: 108, name: "Teal Green", hex: "#006d5b" },
            { id: 109, name: "Emerald Green", hex: "#50c878" },
            { id: 110, name: "Viridian", hex: "#40826d" },
          ],
        },
        {
          id: 12,
          name: "Light Green",
          colors: [
            { id: 111, name: "Lime Green", hex: "#32cd32" },
            { id: 112, name: "Chartreuse", hex: "#7fff00" },
            { id: 113, name: "Spring Green", hex: "#00ff7f" },
            { id: 114, name: "Mint Green", hex: "#98ff98" },
            { id: 115, name: "Seafoam Green", hex: "#2e8b57" },
            { id: 116, name: "Light Sea Green", hex: "#20b2aa" },
            { id: 117, name: "Pale Green", hex: "#98fb98" },
            { id: 118, name: "Aquamarine", hex: "#7fffd4" },
            { id: 119, name: "Light Cyan", hex: "#e0ffff" },
            { id: 120, name: "Turquoise", hex: "#40e0d0" },
          ],
        },
        {
          id: 13,
          name: "Deep Green",
          colors: [
            { id: 121, name: "Forest Green", hex: "#228b22" },
            { id: 122, name: "Dark Green", hex: "#006400" },
            { id: 123, name: "Hunter Green", hex: "#355e3b" },
            { id: 124, name: "Deep Forest Green", hex: "#014421" },
            { id: 125, name: "Olive Drab", hex: "#6b8e23" },
            { id: 126, name: "Evergreen", hex: "#05472a" },
            { id: 127, name: "Teal Green", hex: "#006d5b" },
            { id: 128, name: "Emerald Green", hex: "#50c878" },
            { id: 129, name: "Pine Green", hex: "#01796f" },
            { id: 130, name: "Viridian", hex: "#40826d" },
          ],
        },
        {
          id: 14,
          name: "Rich Green",
          colors: [
            { id: 131, name: "Emerald Green", hex: "#50c878" },
            { id: 132, name: "Jade Green", hex: "#00a86b" },
            { id: 133, name: "Sea Green", hex: "#2e8b57" },
            { id: 134, name: "Forest Green", hex: "#228b22" },
            { id: 135, name: "Dark Green", hex: "#006400" },
            { id: 136, name: "Teal Green", hex: "#006d5b" },
            { id: 137, name: "Hunter Green", hex: "#355e3b" },
            { id: 138, name: "Deep Forest Green", hex: "#014421" },
            { id: 139, name: "Olive Drab", hex: "#6b8e23" },
            { id: 140, name: "Evergreen", hex: "#05472a" },
          ],
        },
        {
          id: 15,
          name: "Vibrant Green",
          colors: [
            { id: 141, name: "Lime Green", hex: "#32cd32" },
            { id: 142, name: "Chartreuse", hex: "#7fff00" },
            { id: 143, name: "Spring Green", hex: "#00ff7f" },
            { id: 144, name: "Emerald Green", hex: "#50c878" },
            { id: 145, name: "Sea Green", hex: "#2e8b57" },
            { id: 146, name: "Forest Green", hex: "#228b22" },
            { id: 147, name: "Teal Green", hex: "#006d5b" },
            { id: 148, name: "Hunter Green", hex: "#355e3b" },
            { id: 149, name: "Jade Green", hex: "#00a86b" },
            { id: 150, name: "Dark Green", hex: "#006400" },
          ],
        },
      ],
    },
    {
      id: 4,
      name: "Yellow",
      img: "https://stppgpaints1prd01.blob.core.windows.net/popular-color/popular-color-belgian-waffle-243-223-182.jpg",
      title: "Yellow Pain Colors",
      content:
        "Yellow paint colors can add buttery charm to a kitchen or bathroom, but in darker yellow tones they can also add a nice earthy feeling to a bedroom or dining room. Check out the yellow paint colors below for more inspiration.",
      hex: "#ddb763",
      collections: [
        {
          id: 16,
          name: "Dark Yellow",
          colors: [
            { id: 151, name: "Goldenrod", hex: "#daa520" },
            { id: 152, name: "Dark Gold", hex: "#b8860b" },
            { id: 153, name: "Mustard", hex: "#ffdb58" },
            { id: 154, name: "Olive", hex: "#808000" },
            { id: 155, name: "Brass", hex: "#b5a642" },
            { id: 156, name: "Amber", hex: "#ffbf00" },
            { id: 157, name: "Saffron", hex: "#f4c430" },
            { id: 158, name: "Topaz", hex: "#ff9933" },
            { id: 159, name: "Butterscotch", hex: "#fdb147" },
            { id: 160, name: "Honey", hex: "#ffd700" },
          ],
        },
        {
          id: 17,
          name: "Light Yellow",
          colors: [
            { id: 161, name: "Lemon", hex: "#fff700" },
            { id: 162, name: "Cornsilk", hex: "#fff8dc" },
            { id: 163, name: "Light Gold", hex: "#ffec8b" },
            { id: 164, name: "Pale Yellow", hex: "#ffff84" },
            { id: 165, name: "Vanilla", hex: "#f3e5ab" },
            { id: 166, name: "Cream", hex: "#ffffcc" },
            { id: 167, name: "Champagne", hex: "#fad6a5" },
            { id: 168, name: "Butter", hex: "#fffdd0" },
            { id: 169, name: "Banana", hex: "#ffe135" },
            { id: 170, name: "Wheat", hex: "#f5deb3" },
          ],
        },
        {
          id: 18,
          name: "Deep Yellow",
          colors: [
            { id: 171, name: "Golden Yellow", hex: "#ffdf00" },
            { id: 172, name: "Sunflower", hex: "#ffac33" },
            { id: 173, name: "Dandelion", hex: "#f0e130" },
            { id: 174, name: "Marigold", hex: "#eaa221" },
            { id: 175, name: "School Bus Yellow", hex: "#ffd800" },
            { id: 176, name: "Yellow Ochre", hex: "#baba00" },
            { id: 177, name: "Goldenrod", hex: "#daa520" },
            { id: 178, name: "Dark Gold", hex: "#b8860b" },
            { id: 179, name: "Butterscotch", hex: "#fdb147" },
            { id: 180, name: "Honey", hex: "#ffd700" },
          ],
        },
        {
          id: 19,
          name: "Rich Yellow",
          colors: [
            { id: 181, name: "Golden Yellow", hex: "#ffdf00" },
            { id: 182, name: "Sunflower", hex: "#ffac33" },
            { id: 183, name: "Dandelion", hex: "#f0e130" },
            { id: 184, name: "Marigold", hex: "#eaa221" },
            { id: 185, name: "School Bus Yellow", hex: "#ffd800" },
            { id: 186, name: "Yellow Ochre", hex: "#baba00" },
            { id: 187, name: "Goldenrod", hex: "#daa520" },
            { id: 188, name: "Dark Gold", hex: "#b8860b" },
            { id: 189, name: "Butterscotch", hex: "#fdb147" },
            { id: 190, name: "Honey", hex: "#ffd700" },
          ],
        },
        {
          id: 20,
          name: "Vibrant Yellow",
          colors: [
            { id: 191, name: "Lemon", hex: "#fff700" },
            { id: 192, name: "Saffron", hex: "#f4c430" },
            { id: 193, name: "Amber", hex: "#ffbf00" },
            { id: 194, name: "Goldenrod", hex: "#daa520" },
            { id: 195, name: "Sunflower", hex: "#ffac33" },
            { id: 196, name: "Dandelion", hex: "#f0e130" },
            { id: 197, name: "Marigold", hex: "#eaa221" },
            { id: 198, name: "School Bus Yellow", hex: "#ffd800" },
            { id: 199, name: "Yellow Ochre", hex: "#baba00" },
            { id: 200, name: "Golden Yellow", hex: "#ffdf00" },
          ],
        },
      ],
    },
    {
      id: 5,
      name: "Orange",
      img: "https://stppgpaints1prd01.blob.core.windows.net/popular-color/popular-color-field-poppy-216-111-60.jpg",
      title: "Orange Paint Colors",
      content:
        "Orange paint colors add joy when used in a kitchen or a bathroom. Orange colors used in living rooms add autumnul grace to your space. Check out the orange paint colors below for the right paint color for your next project.",
      hex: "#d58b5f",
      collections: [
        {
          id: 21,
          name: "Dark Orange",
          colors: [
            { id: 201, name: "Burnt Orange", hex: "#cc5500" },
            { id: 202, name: "Rust", hex: "#b7410e" },
            { id: 203, name: "Bronze", hex: "#cd7f32" },
            { id: 204, name: "Tangerine", hex: "#f28500" },
            { id: 205, name: "Copper", hex: "#b87333" },
            { id: 206, name: "Mahogany", hex: "#420a1d" },
            { id: 207, name: "Terracotta", hex: "#e2725b" },
            { id: 208, name: "Sienna", hex: "#a0522d" },
            { id: 209, name: "Clay", hex: "#b66a50" },
            { id: 210, name: "Umber", hex: "#635147" },
          ],
        },
        {
          id: 22,
          name: "Light Orange",
          colors: [
            { id: 211, name: "Apricot", hex: "#ffb347" },
            { id: 212, name: "Peach", hex: "#ffe5b4" },
            { id: 213, name: "Coral", hex: "#ff7f50" },
            { id: 214, name: "Salmon", hex: "#fa8072" },
            { id: 215, name: "Pumpkin", hex: "#ff7518" },
            { id: 216, name: "Melon", hex: "#ffad99" },
            { id: 217, name: "Cantaloupe", hex: "#ff7e00" },
            { id: 218, name: "Mango", hex: "#ff8243" },
            { id: 219, name: "Creamsicle", hex: "#ffbc48" },
            { id: 220, name: "Peachy Pink", hex: "#ff9a8a" },
          ],
        },
        {
          id: 23,
          name: "Deep Orange",
          colors: [
            { id: 221, name: "Burnt Orange", hex: "#cc5500" },
            { id: 222, name: "Rust", hex: "#b7410e" },
            { id: 223, name: "Copper", hex: "#b87333" },
            { id: 224, name: "Tangerine", hex: "#f28500" },
            { id: 225, name: "Dark Orange", hex: "#ff8c00" },
            { id: 226, name: "Terracotta", hex: "#e2725b" },
            { id: 227, name: "Sienna", hex: "#a0522d" },
            { id: 228, name: "Clay", hex: "#b66a50" },
            { id: 229, name: "Mahogany", hex: "#420a1d" },
            { id: 230, name: "Umber", hex: "#635147" },
          ],
        },
        {
          id: 24,
          name: "Rich Orange",
          colors: [
            { id: 231, name: "Tangerine", hex: "#f28500" },
            { id: 232, name: "Coral", hex: "#ff7f50" },
            { id: 233, name: "Salmon", hex: "#fa8072" },
            { id: 234, name: "Pumpkin", hex: "#ff7518" },
            { id: 235, name: "Burnt Orange", hex: "#cc5500" },
            { id: 236, name: "Dark Orange", hex: "#ff8c00" },
            { id: 237, name: "Apricot", hex: "#ffb347" },
            { id: 238, name: "Peach", hex: "#ffe5b4" },
            { id: 239, name: "Copper", hex: "#b87333" },
            { id: 240, name: "Rust", hex: "#b7410e" },
          ],
        },
        {
          id: 25,
          name: "Vibrant Orange",
          colors: [
            { id: 241, name: "Tangerine", hex: "#f28500" },
            { id: 242, name: "Apricot", hex: "#ffb347" },
            { id: 243, name: "Coral", hex: "#ff7f50" },
            { id: 244, name: "Salmon", hex: "#fa8072" },
            { id: 245, name: "Pumpkin", hex: "#ff7518" },
            { id: 246, name: "Burnt Orange", hex: "#cc5500" },
            { id: 247, name: "Dark Orange", hex: "#ff8c00" },
            { id: 248, name: "Peach", hex: "#ffe5b4" },
            { id: 249, name: "Copper", hex: "#b87333" },
            { id: 250, name: "Rust", hex: "#b7410e" },
          ],
        },
      ],
    },
    {
      id: 6,
      name: "Purple",
      img: "https://www.ppgpaints.com/cms/getmedia/4cdfe670-c3b0-4118-b0f1-2d311d765e81/room-living-room_grape-juice__ppg1251-7.jpg",
      title: "Purple Paint Colors",
      content:
        "Purple paint colors are bold, regal, and even tranquil depending on the tone. From luxurious lavenders in the bathroom, to deep winesap purples in the dining room - purple paint colors work in almost every room of the house. To find the right purple paint color for your next painting project, please click the link below.",
      hex: "#9e88aa",
      collections: [
        {
          id: 26,
          name: "Dark Purple",
          colors: [
            { id: 251, name: "Indigo", hex: "#4b0082" },
            { id: 252, name: "Eggplant", hex: "#614051" },
            { id: 253, name: "Plum", hex: "#8e4585" },
            { id: 254, name: "Grape", hex: "#6f2da8" },
            { id: 255, name: "Blackberry", hex: "#4d0a4d" },
            { id: 256, name: "Mulberry", hex: "#c54b8c" },
            { id: 257, name: "Aubergine", hex: "#3d0734" },
            { id: 258, name: "Mauve", hex: "#915f6d" },
            { id: 259, name: "Tyrian Purple", hex: "#66023c" },
            { id: 260, name: "Regal Purple", hex: "#6a287e" },
          ],
        },
        {
          id: 27,
          name: "Light Purple",
          colors: [
            { id: 261, name: "Lavender", hex: "#e6e6fa" },
            { id: 262, name: "Lilac", hex: "#c8a2c8" },
            { id: 263, name: "Periwinkle", hex: "#ccccff" },
            { id: 264, name: "Amethyst", hex: "#9966cc" },
            { id: 265, name: "Orchid", hex: "#da70d6" },
            { id: 266, name: "Thistle", hex: "#d8bfd8" },
            { id: 267, name: "Mauve", hex: "#915f6d" },
            { id: 268, name: "Wisteria", hex: "#c9a0dc" },
            { id: 269, name: "Heather", hex: "#b7c3d0" },
            { id: 270, name: "Heather", hex: "#b7c3d0" },
          ],
        },
        {
          id: 28,
          name: "Deep Purple",
          colors: [
            { id: 271, name: "Indigo", hex: "#4b0082" },
            { id: 272, name: "Eggplant", hex: "#614051" },
            { id: 273, name: "Plum", hex: "#8e4585" },
            { id: 274, name: "Grape", hex: "#6f2da8" },
            { id: 275, name: "Blackberry", hex: "#4d0a4d" },
            { id: 276, name: "Mulberry", hex: "#c54b8c" },
            { id: 277, name: "Aubergine", hex: "#3d0734" },
            { id: 278, name: "Mauve", hex: "#915f6d" },
            { id: 279, name: "Tyrian Purple", hex: "#66023c" },
            { id: 280, name: "Regal Purple", hex: "#6a287e" },
          ],
        },
        {
          id: 29,
          name: "Rich Purple",
          colors: [
            { id: 281, name: "Plum", hex: "#8e4585" },
            { id: 282, name: "Grape", hex: "#6f2da8" },
            { id: 283, name: "Blackberry", hex: "#4d0a4d" },
            { id: 284, name: "Mulberry", hex: "#c54b8c" },
            { id: 285, name: "Aubergine", hex: "#3d0734" },
            { id: 286, name: "Mauve", hex: "#915f6d" },
            { id: 287, name: "Tyrian Purple", hex: "#66023c" },
            { id: 288, name: "Regal Purple", hex: "#6a287e" },
            { id: 289, name: "Indigo", hex: "#4b0082" },
            { id: 290, name: "Eggplant", hex: "#614051" },
          ],
        },
        {
          id: 30,
          name: "Vibrant Purple",
          colors: [
            { id: 291, name: "Amethyst", hex: "#9966cc" },
            { id: 292, name: "Orchid", hex: "#da70d6" },
            { id: 293, name: "Lavender", hex: "#e6e6fa" },
            { id: 294, name: "Lilac", hex: "#c8a2c8" },
            { id: 295, name: "Periwinkle", hex: "#ccccff" },
            { id: 296, name: "Thistle", hex: "#d8bfd8" },
            { id: 297, name: "Wisteria", hex: "#c9a0dc" },
            { id: 298, name: "Heather", hex: "#b7c3d0" },
            { id: 299, name: "Heather", hex: "#b7c3d0" },
            { id: 300, name: "Regal Purple", hex: "#6a287e" },
          ],
        },
      ],
    },
    {
      id: 7,
      name: "Pink",
      img: "https://stppgpaints1prd01.blob.core.windows.net/popular-color/popular-color-mountain-laurel-244-200-213.jpg",
      title: "Pink Paint Colors",
      content:
        "Pink paint colors are lively and full of fun. Use pink colors in bedrooms for playful charm, or in a kitchen for a mid-1950s look. Check out the pink paint colors below for your next project!",
      hex: "#e5bfbc",
      collections: [
        {
          id: 31,
          name: "Dark Pink",
          colors: [
            { id: 301, name: "Fuchsia", hex: "#ff00ff" },
            { id: 302, name: "Magenta", hex: "#ff00ff" },
            { id: 303, name: "Deep Pink", hex: "#ff1493" },
            { id: 304, name: "Hot Pink", hex: "#ff69b4" },
            { id: 305, name: "Rose", hex: "#ff007f" },
            { id: 306, name: "Raspberry", hex: "#e30b5d" },
            { id: 307, name: "Ruby", hex: "#e0115f" },
            { id: 308, name: "Crimson", hex: "#dc143c" },
            { id: 309, name: "Cerise", hex: "#de3163" },
            { id: 310, name: "Burgundy", hex: "#800020" },
          ],
        },
        {
          id: 32,
          name: "Light Pink",
          colors: [
            { id: 311, name: "Bubble Gum Pink", hex: "#ffc1cc" },
            { id: 312, name: "Cotton Candy Pink", hex: "#ffbcd9" },
            { id: 313, name: "Baby Pink", hex: "#f4c2c2" },
            { id: 314, name: "Cherry Blossom Pink", hex: "#ffc3cd" },
            { id: 315, name: "Salmon Pink", hex: "#ff91a4" },
            { id: 316, name: "Flamingo Pink", hex: "#fc8eac" },
            { id: 317, name: "Peachy Pink", hex: "#ff9a8a" },
            { id: 318, name: "Rose Quartz Pink", hex: "#bd559c" },
            { id: 319, name: "Orchid Pink", hex: "#f2bdc7" },
            { id: 320, name: "Strawberry Pink", hex: "#ff6090" },
          ],
        },
        {
          id: 33,
          name: "Deep Pink",
          colors: [
            { id: 321, name: "Fuchsia", hex: "#ff00ff" },
            { id: 322, name: "Magenta", hex: "#ff00ff" },
            { id: 323, name: "Deep Pink", hex: "#ff1493" },
            { id: 324, name: "Hot Pink", hex: "#ff69b4" },
            { id: 325, name: "Rose", hex: "#ff007f" },
            { id: 326, name: "Raspberry", hex: "#e30b5d" },
            { id: 327, name: "Ruby", hex: "#e0115f" },
            { id: 328, name: "Crimson", hex: "#dc143c" },
            { id: 329, name: "Cerise", hex: "#de3163" },
            { id: 330, name: "Burgundy", hex: "#800020" },
          ],
        },
        {
          id: 34,
          name: "Rich Pink",
          colors: [
            { id: 331, name: "Hot Pink", hex: "#ff69b4" },
            { id: 332, name: "Rose", hex: "#ff007f" },
            { id: 333, name: "Raspberry", hex: "#e30b5d" },
            { id: 334, name: "Ruby", hex: "#e0115f" },
            { id: 335, name: "Crimson", hex: "#dc143c" },
            { id: 336, name: "Cerise", hex: "#de3163" },
            { id: 337, name: "Burgundy", hex: "#800020" },
            { id: 338, name: "Deep Pink", hex: "#ff1493" },
            { id: 339, name: "Fuchsia", hex: "#ff00ff" },
            { id: 340, name: "Magenta", hex: "#ff00ff" },
          ],
        },
        {
          id: 35,
          name: "Vibrant Pink",
          colors: [
            { id: 341, name: "Hot Pink", hex: "#ff69b4" },
            { id: 342, name: "Bubble Gum Pink", hex: "#ffc1cc" },
            { id: 343, name: "Cotton Candy Pink", hex: "#ffbcd9" },
            { id: 344, name: "Baby Pink", hex: "#f4c2c2" },
            { id: 345, name: "Cherry Blossom Pink", hex: "#ffc3cd" },
            { id: 346, name: "Flamingo Pink", hex: "#fc8eac" },
            { id: 347, name: "Peachy Pink", hex: "#ff9a8a" },
            { id: 348, name: "Rose Quartz Pink", hex: "#bd559c" },
            { id: 349, name: "Orchid Pink", hex: "#f2bdc7" },
            { id: 350, name: "Strawberry Pink", hex: "#ff6090" },
          ],
        },
      ],
    },
    {
      id: 8,
      name: "Gray",
      img: "https://stppgpaints1prd01.blob.core.windows.net/popular-color/popular-color-flagstone-172-173-173.jpg",
      title: "Gray Pain Colors",
      content:
        "Gray paint colors effortlessly blend modernity with classic charm, making them a versatile choice for any space. Whether you're aiming for a hip and trendy look in your living room or seeking to create a mood in your bedroom or dining room, gray can provide the perfect backdrop. Its understated elegance and ability to complement a variety of decor styles make gray a go-to color for those looking to achieve a stylish and timeless aesthetic.",
      hex: "#929292",
      collections: [
        {
          id: 36,
          name: "Dark Gray",
          colors: [
            { id: 351, name: "Charcoal", hex: "#36454f" },
            { id: 352, name: "Graphite", hex: "#434c52" },
            { id: 353, name: "Slate", hex: "#708090" },
            { id: 354, name: "Gunmetal", hex: "#2a3439" },
            { id: 355, name: "Ash", hex: "#b2beb5" },
            { id: 356, name: "Lead", hex: "#2e3d46" },
            { id: 357, name: "Taupe", hex: "#483c32" },
            { id: 358, name: "Stormy Gray", hex: "#717d7e" },
            { id: 359, name: "Ebony", hex: "#555d50" },
            { id: 360, name: "Thunder", hex: "#191970" },
          ],
        },
        {
          id: 37,
          name: "Light Gray",
          colors: [
            { id: 361, name: "Silver", hex: "#c0c0c0" },
            { id: 362, name: "Platinum", hex: "#e5e4e2" },
            { id: 363, name: "Smoke", hex: "#738276" },
            { id: 364, name: "Mist", hex: "#c4c4c4" },
            { id: 365, name: "Pearl", hex: "#eae0c8" },
            { id: 366, name: "Cloud", hex: "#f0f8ff" },
            { id: 367, name: "Dove", hex: "#e1e1e1" },
            { id: 368, name: "Fog", hex: "#dfe2e5" },
            { id: 369, name: "Lunar Gray", hex: "#b2beb5" },
            { id: 370, name: "Gainsboro", hex: "#dcdcdc" },
          ],
        },
        {
          id: 38,
          name: "Warm Gray",
          colors: [
            { id: 371, name: "Taupe", hex: "#483c32" },
            { id: 372, name: "Stormy Gray", hex: "#717d7e" },
            { id: 373, name: "Pewter", hex: "#8e8e8e" },
            { id: 374, name: "Driftwood", hex: "#af937d" },
            { id: 375, name: "Warm Gray", hex: "#808080" },
            { id: 376, name: "Battleship Gray", hex: "#848482" },
            { id: 377, name: "Cement", hex: "#8e8e8e" },
            { id: 378, name: "Cobblestone", hex: "#8b8378" },
            { id: 379, name: "Ash Gray", hex: "#b2beb5" },
            { id: 380, name: "Nickel", hex: "#727472" },
          ],
        },
        {
          id: 39,
          name: "Cool Gray",
          colors: [
            { id: 381, name: "Silver", hex: "#c0c0c0" },
            { id: 382, name: "Platinum", hex: "#e5e4e2" },
            { id: 383, name: "Smoke", hex: "#738276" },
            { id: 384, name: "Mist", hex: "#c4c4c4" },
            { id: 385, name: "Pearl", hex: "#eae0c8" },
            { id: 386, name: "Cloud", hex: "#f0f8ff" },
            { id: 387, name: "Dove", hex: "#e1e1e1" },
            { id: 388, name: "Fog", hex: "#dfe2e5" },
            { id: 389, name: "Lunar Gray", hex: "#b2beb5" },
            { id: 390, name: "Gainsboro", hex: "#dcdcdc" },
          ],
        },
        {
          id: 40,
          name: "Neutral Gray",
          colors: [
            { id: 391, name: "Ash", hex: "#b2beb5" },
            { id: 392, name: "Lead", hex: "#2e3d46" },
            { id: 393, name: "Stormy Gray", hex: "#717d7e" },
            { id: 394, name: "Ebony", hex: "#555d50" },
            { id: 395, name: "Taupe", hex: "#483c32" },
            { id: 396, name: "Slate", hex: "#708090" },
            { id: 397, name: "Charcoal", hex: "#36454f" },
            { id: 398, name: "Gunmetal", hex: "#2a3439" },
            { id: 399, name: "Graphite", hex: "#434c52" },
            { id: 400, name: "Silver", hex: "#c0c0c0" },
          ],
        },
      ],
    },
    {
      id: 9,
      name: "Black",
      img: "https://stppgpaints1prd01.blob.core.windows.net/popular-color/popular-color-black-magic-65-64-64.jpg",
      title: "Black Paint Colors",
      content:
        "Black paint colors are not monolithic - they come in a variety of tones and hues that give both life and energy to a room. Use them to add class to trim, or with an accent wall to really give a hip look to a room.",
      hex: "#535353",
      collections: [
        {
          id: 41,
          name: "Dark Black",
          colors: [
            { id: 401, name: "Jet Black", hex: "#080808" },
            { id: 402, name: "Midnight Black", hex: "#2b2b2b" },
            { id: 403, name: "Ebony", hex: "#555d50" },
            { id: 404, name: "Charcoal", hex: "#36454f" },
            { id: 405, name: "Onyx", hex: "#353839" },
            { id: 406, name: "Pitch Black", hex: "#000000" },
            { id: 407, name: "Obsidian", hex: "#191970" },
            { id: 408, name: "Coal", hex: "#080808" },
            { id: 409, name: "Raven", hex: "#0e0e10" },
            { id: 410, name: "Soot", hex: "#1a1a1a" },
          ],
        },
        {
          id: 42,
          name: "Light Black",
          colors: [
            { id: 411, name: "Shadow", hex: "#212121" },
            { id: 412, name: "Night", hex: "#2c3e50" },
            { id: 413, name: "Coal", hex: "#080808" },
            { id: 414, name: "Pitch Black", hex: "#000000" },
            { id: 415, name: "Ebony", hex: "#555d50" },
            { id: 416, name: "Charcoal", hex: "#36454f" },
            { id: 417, name: "Onyx", hex: "#353839" },
            { id: 418, name: "Jet Black", hex: "#080808" },
            { id: 419, name: "Midnight Black", hex: "#2b2b2b" },
            { id: 420, name: "Obsidian", hex: "#191970" },
          ],
        },
        {
          id: 43,
          name: "Pure Black",
          colors: [
            { id: 421, name: "Pitch Black", hex: "#000000" },
            { id: 422, name: "Jet Black", hex: "#080808" },
            { id: 423, name: "Midnight Black", hex: "#2b2b2b" },
            { id: 424, name: "Ebony", hex: "#555d50" },
            { id: 425, name: "Charcoal", hex: "#36454f" },
            { id: 426, name: "Onyx", hex: "#353839" },
            { id: 427, name: "Obsidian", hex: "#191970" },
            { id: 428, name: "Coal", hex: "#080808" },
            { id: 429, name: "Raven", hex: "#0e0e10" },
            { id: 430, name: "Soot", hex: "#1a1a1a" },
          ],
        },
        {
          id: 44,
          name: "Deep Black",
          colors: [
            { id: 431, name: "Pitch Black", hex: "#000000" },
            { id: 432, name: "Jet Black", hex: "#080808" },
            { id: 433, name: "Midnight Black", hex: "#2b2b2b" },
            { id: 434, name: "Ebony", hex: "#555d50" },
            { id: 435, name: "Charcoal", hex: "#36454f" },
            { id: 436, name: "Onyx", hex: "#353839" },
            { id: 437, name: "Obsidian", hex: "#191970" },
            { id: 438, name: "Coal", hex: "#080808" },
            { id: 439, name: "Raven", hex: "#0e0e10" },
            { id: 440, name: "Soot", hex: "#1a1a1a" },
          ],
        },
        {
          id: 45,
          name: "Matte Black",
          colors: [
            { id: 441, name: "Pitch Black", hex: "#000000" },
            { id: 442, name: "Jet Black", hex: "#080808" },
            { id: 443, name: "Midnight Black", hex: "#2b2b2b" },
            { id: 444, name: "Ebony", hex: "#555d50" },
            { id: 445, name: "Charcoal", hex: "#36454f" },
            { id: 446, name: "Onyx", hex: "#353839" },
            { id: 447, name: "Obsidian", hex: "#191970" },
            { id: 448, name: "Coal", hex: "#080808" },
            { id: 449, name: "Raven", hex: "#0e0e10" },
            { id: 450, name: "Soot", hex: "#1a1a1a" },
          ],
        },
      ],
    },
    {
      id: 10,
      name: "White",
      img: "https://stppgpaints1prd01.blob.core.windows.net/popular-color/popular-color-delicate-white-241-242-238.jpg",
      title: "White Paint Colors",
      content:
        "White paint colors give space to rooms as well as bring in light. Have a small room you want to expand or a space you need to give a sense of peace? Choose a brilliant white from our white paint color palette below.",
      hex: "#ebe9d7",
      collections: [
        {
          id: 46,
          name: "Pure White",
          colors: [
            { id: 451, name: "Snow White", hex: "#fffafa" },
            { id: 452, name: "Ivory", hex: "#fffff0" },
            { id: 453, name: "Cream", hex: "#fffdd0" },
            { id: 454, name: "Pearl White", hex: "#f9f9f9" },
            { id: 455, name: "Eggshell", hex: "#f0ead6" },
            { id: 456, name: "Linen White", hex: "#faf0e6" },
            { id: 457, name: "Ghost White", hex: "#f8f8ff" },
            { id: 458, name: "Chiffon", hex: "#f0f8ff" },
            { id: 459, name: "Magnolia", hex: "#f8f4ff" },
            { id: 460, name: "Lily", hex: "#f8f8f8" },
          ],
        },
        {
          id: 47,
          name: "Bright White",
          colors: [
            { id: 461, name: "Snow White", hex: "#fffafa" },
            { id: 462, name: "Ivory", hex: "#fffff0" },
            { id: 463, name: "Cream", hex: "#fffdd0" },
            { id: 464, name: "Pearl White", hex: "#f9f9f9" },
            { id: 465, name: "Eggshell", hex: "#f0ead6" },
            { id: 466, name: "Linen White", hex: "#faf0e6" },
            { id: 467, name: "Ghost White", hex: "#f8f8ff" },
            { id: 468, name: "Chiffon", hex: "#f0f8ff" },
            { id: 469, name: "Magnolia", hex: "#f8f4ff" },
            { id: 470, name: "Lily", hex: "#f8f8f8" },
          ],
        },
        {
          id: 48,
          name: "Soft White",
          colors: [
            { id: 471, name: "Snow White", hex: "#fffafa" },
            { id: 472, name: "Ivory", hex: "#fffff0" },
            { id: 473, name: "Cream", hex: "#fffdd0" },
            { id: 474, name: "Pearl White", hex: "#f9f9f9" },
            { id: 475, name: "Eggshell", hex: "#f0ead6" },
            { id: 476, name: "Linen White", hex: "#faf0e6" },
            { id: 477, name: "Ghost White", hex: "#f8f8ff" },
            { id: 478, name: "Chiffon", hex: "#f0f8ff" },
            { id: 479, name: "Magnolia", hex: "#f8f4ff" },
            { id: 480, name: "Lily", hex: "#f8f8f8" },
          ],
        },
        {
          id: 49,
          name: "Warm White",
          colors: [
            { id: 481, name: "Snow White", hex: "#fffafa" },
            { id: 482, name: "Ivory", hex: "#fffff0" },
            { id: 483, name: "Cream", hex: "#fffdd0" },
            { id: 484, name: "Pearl White", hex: "#f9f9f9" },
            { id: 485, name: "Eggshell", hex: "#f0ead6" },
            { id: 486, name: "Linen White", hex: "#faf0e6" },
            { id: 487, name: "Ghost White", hex: "#f8f8ff" },
            { id: 488, name: "Chiffon", hex: "#f0f8ff" },
            { id: 489, name: "Magnolia", hex: "#f8f4ff" },
            { id: 490, name: "Lily", hex: "#f8f8f8" },
          ],
        },
        {
          id: 50,
          name: "Cool White",
          colors: [
            { id: 491, name: "Snow White", hex: "#fffafa" },
            { id: 492, name: "Ivory", hex: "#fffff0" },
            { id: 493, name: "Cream", hex: "#fffdd0" },
            { id: 494, name: "Pearl White", hex: "#f9f9f9" },
            { id: 495, name: "Eggshell", hex: "#f0ead6" },
            { id: 496, name: "Linen White", hex: "#faf0e6" },
            { id: 497, name: "Ghost White", hex: "#f8f8ff" },
            { id: 498, name: "Chiffon", hex: "#f0f8ff" },
            { id: 499, name: "Magnolia", hex: "#f8f4ff" },
            { id: 500, name: "Lily", hex: "#f8f8f8" },
          ],
        },
      ],
    },
  ],
  colorsSearch: "",
};

export const colorFamilies = createSlice({
  name: "ColorFamilies",
  initialState: initialState,
  reducers: {
    setSearchColors(state, action) {
      state.colorsSearch = action.payload;
    },
  },
});
export const { setSearchColors } = colorFamilies.actions;

export default colorFamilies.reducer;
